### ISSUE TITLE
Auto-Install Dependencies?

### ISSUE THREAD

**Issue by ric-evans** [eWaterCycle/setup-apptainer#21]
This action has been helpful, but there's one thing I've come across. Currently, running `setup-apptainer` alone results in apptainer failing to install, complaining about missing `squashfuse` and `fuse2fs`:
```
build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: eWaterCycle/setup-apptainer@v1
        with:
          apptainer-version: 1.1.2
```

```
...
Unpacking apptainer (1.1.2) ...
dpkg: dependency problems prevent configuration of apptainer:
 apptainer depends on squashfuse; however:
  Package squashfuse is not installed.
 apptainer depends on fuse2fs; however:
  Package fuse2fs is not installed.

dpkg: error processing package apptainer (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 apptainer
Error: The process '/usr/bin/sudo' failed with exit code 1
```

The install works if we install these explicitly:
```
build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Apptainer/Singularity Deps
        run: |
          sudo apt-get -y install squashfuse fuse2fs
      - uses: eWaterCycle/setup-apptainer@v1
        with:
          apptainer-version: 1.1.2
```

It would be nice if `setup-apptainer` did this automatically.
